export const USERS_REQUEST: "USERS_REQUEST" = "USERS_REQUEST";
export const USERS_SUCCESS: "USERS_SUCCESS" = "USERS_SUCCESS";
export const USERS_ERROR: "USERS_ERROR" = "USERS_ERROR";

export const SORT_MODE: "SORT_MODE" = "SORT_MODE";

export const PREVIEW_USER: "PREVIEW_USER" = "PREVIEW_USER";